### ISSUE TITLE
Firefox 39 Uint8Array Error

### ISSUE THREAD

**Issue by joaopms** [caseif/vis#1]
Using Firefox 39 (latest beta) the visualizer doesn't work, printing the following error to the console:

> TypeError: invalid arguments (at vis.js:359:16)

[Line in question](https://github.com/caseif/vis/blob/master/js/vis.js#L359)

**Comment by caseif** [comment]
Seems to be a floating-point rounding error. Of course...

**Comment by caseif** [comment]
Fixed via [b499318a](https://github.com/caseif/vis/commit/b499318a).
