### ISSUE TITLE
Licensing & "libraryfication"

### ISSUE THREAD

**Issue by ghost** [caseif/vis#10]
Hey,
1. Would you mind licensing the project under a MIT license? I'd like to include it in my (not released yet) project.
2. I'm slowly turning it into a reusable component (JS library), are you interested in the results? This would allow for it to be easily used on audio elements (e.g. Soundcloud streams).

![2_167](https://cloud.githubusercontent.com/assets/6376571/8873652/a60a5e0c-31d6-11e5-9840-51f94f336b14.png)

Thanks.

**Comment by caseif** [comment]
1. It's already licensed under BSD-new, which should be fine for your purposes.
2. I would be interested to see; I'd ask you to get in touch via email at [me@caseif.net](mailto:me@caseif.net).
