### ISSUE TITLE
Mirai Sekai Background Missing and the last bar from the vis it looks it is cutt in half

### ISSUE THREAD

**Issue by GiovanniMCMXCIX** [caseif/vis#12]
![error1](https://cloud.githubusercontent.com/assets/10764652/9665438/00801c38-5279-11e5-9ce7-e44f93ac9300.PNG)
![error2](https://cloud.githubusercontent.com/assets/10764652/9665434/0075ddea-5279-11e5-8dbe-a710c0845e06.PNG)
![error3](https://cloud.githubusercontent.com/assets/10764652/9665435/0078d37e-5279-11e5-98b2-519bc64f692f.PNG)
![error4](https://cloud.githubusercontent.com/assets/10764652/9665437/007ea7d6-5279-11e5-8201-50ac55f15933.PNG)
![error5](https://cloud.githubusercontent.com/assets/10764652/9665436/007ad39a-5279-11e5-963a-42aee06ab537.PNG)
Fist time I opened on a song with "Mirai Sekai" as genre I was getting the "Failed to get resources" error, now is getting the error "403 (OK)"

**Comment by caseif** [comment]
Thanks for the report. I'll take a closer look at it later today and fix it ASAP.

**Comment by caseif** [comment]
Christ, I forgot to set permissions on the video on Google Drive.The video should work now. I'll keep this ticket open since the bar cropping is an issue which needs to be fixed separately.
