### ISSUE TITLE
Special characters in keys prevent loading

### ISSUE THREAD

**Issue by TheBlackParrot** [caseif/vis#14]
I'm unsure if incept.gq is the same as what's listed on the readme, but http://incept.gq/?song=jackÜwherearedarrenst455b is broken.  
Maybe throw an error if anything the key is using for characters isn't alpha-numeric?

**Comment by caseif** [comment]
I'll investigate when I get home later today.

**Comment by itsIncept** [comment]
This is kinda a problem with my site because my PHP doesn't remove those kind of characters. Caseif does his manually so it's not an issue for his site.

**Comment by itsIncept** [comment]
This should be fixed now, you can enter something like "Jack Ü" into the title box and it will convert it when outputting a key.
