### ISSUE TITLE
Specials not in the list of choices

### ISSUE THREAD

**Issue by karst** [caseif/vis#3]
Tracks like album mixes, Hold Fast, Mirai Sekai, What I've Waited For, Champions, Monstercat Live Performance by Didrick and some more.
These tracks have an imaged background (or black), with white bars, the logo is white too, with either a black monstercat logo or look through logo in it.
![f1dc53c0af8db7d58d5a91e9d4146fa3](https://cloud.githubusercontent.com/assets/1516893/8252999/92a86cb6-168b-11e5-963f-50d58d381dc4.jpg)

**Comment by itsIncept** [comment]
Will work on it.

**Comment by karst** [comment]
awesome :)

**Comment by itsIncept** [comment]
waiting for approval on my fork but here's what it looks like http://i.imgur.com/3KEdsVB.jpg

**Comment by karst** [comment]
looks very nice :)

**Comment by karst** [comment]
Does it work with the background like you have to give an input image? Like an i.imgur.com/<code> .png jpg gif ?

**Comment by itsIncept** [comment]
I can add that, but this isn't exactly a user customizable (friendly) project as of yet so it would be a per case basis at the moment.
Hold Fast: http://imgur.com/tD0uizY

**Comment by karst** [comment]
alright :)

**Comment by caseif** [comment]
I'm hesitant to customize every track that doesn't follow the standard format. After a while it very well could get messy and we'll have too many wallpaper-sized backgrounds in the images folder.
