### ISSUE TITLE
how do i work this thing

### ISSUE THREAD

**Issue by nullfaun4** [caseif/vis#9]
i do not know how to work this visualiser. does it even work in ubuntu

**Comment by GiovanniMCMXCIX** [comment]
Which browser you use?

**Comment by nullfaun4** [comment]
firefox

**Comment by GiovanniMCMXCIX** [comment]
Do right click on visualiser and select "Inspect Element" and put screen shot with the inspect tab

**Comment by nullfaun4** [comment]
![screenshot from 2015-06-30 12 00 07](https://cloud.githubusercontent.com/assets/13121260/8435512/9a7d5cd4-1f1f-11e5-991d-b6af20c328e4.png)

**Comment by GiovanniMCMXCIX** [comment]
No, like this
![capture5](https://cloud.githubusercontent.com/assets/10764652/8435579/b15cca76-1f5a-11e5-8a5f-74a08baba435.PNG)

**Comment by GiovanniMCMXCIX** [comment]
or just screenshoot the page with the Inspect tab

**Comment by nullfaun4** [comment]
i do not have that  should i be using chrome ?

(do you mean the console)

**Comment by GiovanniMCMXCIX** [comment]
yes i mean the console

**Comment by nullfaun4** [comment]
ok
![screenshot from 2015-06-30 12 11 59](https://cloud.githubusercontent.com/assets/13121260/8435774/3c1f0690-1f21-11e5-8e2b-c0878393d677.png)

**Comment by GiovanniMCMXCIX** [comment]
Now wait for Caseif too see this

**Comment by nullfaun4** [comment]
ok

**Comment by caseif** [comment]
Does this occur on your own hosted version of vis.js?

**Comment by nullfaun4** [comment]
im sorry i dont know what you mean 
i did not add any code if that is what you mean

**Comment by GiovanniMCMXCIX** [comment]
The error is from vis.caseif.net visualiser or from your own hosted version of the visualiser?

**Comment by nullfaun4** [comment]
my own hosted version

**Comment by caseif** [comment]
Ah, there's the issue. I had meant to put something about this in the README, but Javascript doesn't like it when you request resources from another domain if a certain header isn't set. My solution on my hosted version has been to set up a reverse proxy on my own domain to docs.google.com to bypass this restriction and serve the content through vis.caseif.net.

**Comment by nullfaun4** [comment]
also the site returns this error
![screenshot from 2015-06-30 21 28 00](https://cloud.githubusercontent.com/assets/13121260/8445725/eac026fa-1f6e-11e5-8c72-a21ff762a86e.png)

**Comment by caseif** [comment]
I'll set up CloudFlare to ignore the vis subdomain.
